import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import type { ProjectConfig } from '../src/types.js';
import { createTask } from './db.js';
import { attachTaskBinding } from './taskBinding.js';
import { getResourceRegistry } from './resourceRegistry.js';
import { createExecutorJob, getExecutorJob, getExecutorSnapshot } from './executorStore.js';
import { projectScopedExecutorPayload } from './executorRouting.js';

export const CAPABILITY_SMOKE_MARKER = '<!-- BRIDGE_CAPABILITY_SMOKE_V1 -->';
type CapabilityName = 'workspace_read'|'workspace_write'|'github_read'|'github_write';
type Check = { status:'pending'|'pass'|'fail'; checked_at:string|null; reason:string|null };
export interface CapabilitySmoke { smoke_id:string; workspace_id:string; project_id:string; target_id:string; agent_instance_id:string; provider:string; nonce:string; temp_path:string; source_path:string; expected_source_sha256:string; task_id:string; verify_job_id:string|null; created_at:string; updated_at:string; cleanup_status:'pending'|'reported'; capabilities:Record<CapabilityName,Check>; }
interface Store { version:1; smokes:CapabilitySmoke[] }
let tail=Promise.resolve();
function storePath(){return path.resolve(process.cwd(),process.env.BRIDGE_CAPABILITY_SMOKE_PATH||'data/capability-smokes.json')}
function readStore():Store{try{const x=JSON.parse(fs.readFileSync(storePath(),'utf8'));return x?.version===1&&Array.isArray(x.smokes)?x:{version:1,smokes:[]}}catch{return{version:1,smokes:[]}}}
function writeStore(s:Store){const f=storePath();fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(s,null,2)+'\n')}
async function locked<T>(fn:()=>Promise<T>){let release!:()=>void;const prev=tail;tail=new Promise<void>(r=>release=r);await prev;try{return await fn()}finally{release()}}
const pending=():Check=>({status:'pending',checked_at:null,reason:null});
function githubContentsUrl(repo:string,branch:string,file:string){const u=new URL(repo);if(u.hostname!=='github.com')throw new Error('Capability smoke currently requires a github.com repository URL');const p=u.pathname.replace(/^\/+|\/+$/g,'').replace(/\.git$/,'');return `https://api.github.com/repos/${p}/contents/${file}?ref=${encodeURIComponent(branch||'main')}`}
async function githubFile(repo:string,branch:string,file:string){const r=await fetch(githubContentsUrl(repo,branch,file),{headers:{Accept:'application/vnd.github.raw+json','User-Agent':'Bridge-Capability-Smoke'}});if(r.status===404)return null;if(!r.ok)throw new Error(`GitHub verify HTTP ${r.status}`);return await r.text()}
export async function startCapabilitySmoke(project:ProjectConfig,workspaceId:string,targetId:string){return locked(async()=>{const registry=await getResourceRegistry(project);const ws=registry.workspaces.find(w=>w.workspace_id===workspaceId);if(!ws)throw new Error(`workspace ${workspaceId} not found`);const target=[...ws.chatgpt_targets,...ws.studio_targets].find(t=>t.target_id===targetId);if(!target)throw new Error(`target ${targetId} not found in workspace ${workspaceId}`);const sourceText=await githubFile(ws.repository_url,ws.branch,'START_HERE.md');if(sourceText===null)throw new Error('START_HERE.md not found on canonical GitHub branch');const expectedSourceSha256=crypto.createHash('sha256').update(sourceText).digest('hex');const nonce=crypto.randomBytes(16).toString('hex');const smokeId=`CAP-${Date.now().toString(36)}-${crypto.randomBytes(3).toString('hex')}`;const tempPath=`.bridge/capability-smoke/${target.target_id}-${nonce}.txt`;const description=[CAPABILITY_SMOKE_MARKER,`smoke_id=${smokeId}`,`nonce=${nonce}`,`source_path=START_HERE.md`,`temp_path=${tempPath}`,'Perform only this capability proof on the bound workspace/target.','1) Read source_path from the bound LOCAL workspace. Write temp_path locally with EXACT content: nonce=<nonce>\\nsource_sha256=<sha256 of LOCAL source_path>\\n','2) Read source_path from canonical GitHub branch. Create/commit temp_path on that GitHub branch with EXACT content: nonce=<nonce>\\nsource_sha256=<sha256 of GITHUB source_path>\\n','3) POST the smoke verify endpoint for this smoke_id. Bridge will independently verify local and GitHub temp contents; do not claim PASS yourself.','4) Poll the smoke GET endpoint until verification is terminal. Then delete BOTH temp files (local and GitHub) and POST cleanup.','Do not modify any other project file.'].join('\n').replaceAll('<nonce>',nonce);const bound=attachTaskBinding(description,{workspace_id:ws.workspace_id,project_id:ws.project_id,agent_instance_id:target.agent_instance_id});const task=await createTask({title:`Capability smoke ${target.label}`,description:bound.description,assignee:target.provider==='google-ai-studio'?'gemini':'chatgpt',created_by:'chatgpt',priority:'high',status:'assigned'});const now=new Date().toISOString();const smoke:CapabilitySmoke={smoke_id:smokeId,workspace_id:ws.workspace_id,project_id:ws.project_id,target_id:target.target_id,agent_instance_id:target.agent_instance_id,provider:target.provider,nonce,temp_path:tempPath,source_path:'START_HERE.md',expected_source_sha256:expectedSourceSha256,task_id:task.id,verify_job_id:null,created_at:now,updated_at:now,cleanup_status:'pending',capabilities:{workspace_read:pending(),workspace_write:pending(),github_read:pending(),github_write:pending()}};const s=readStore();s.smokes.unshift(smoke);writeStore(s);return smoke})}
export async function getCapabilitySmoke(project:ProjectConfig,smokeId:string){const s=readStore();const smoke=s.smokes.find(x=>x.smoke_id===smokeId);if(!smoke)return null;const registry=await getResourceRegistry(project);const ws=registry.workspaces.find(w=>w.workspace_id===smoke.workspace_id&&w.project_id===smoke.project_id);if(!ws)return smoke;if(smoke.verify_job_id&&smoke.capabilities.workspace_write.status==='pending'){const job=await getExecutorJob(smoke.verify_job_id);if(job&&['completed','failed','cancelled'].includes(job.status)){const now=new Date().toISOString();const text=String((job.result as any)?.data?.content??(job.result as any)?.content??(job.result as any)?.stdout??'');const ok=job.status==='completed'&&text===`nonce=${smoke.nonce}\nsource_sha256=${smoke.expected_source_sha256}\n`;smoke.capabilities.workspace_write={status:ok?'pass':'fail',checked_at:now,reason:ok?'Bridge executor independently read exact nonce file':'Local nonce file missing or content mismatch'};smoke.capabilities.workspace_read={status:ok?'pass':'fail',checked_at:now,reason:ok?'Nonce file proves agent read requested local source before write':'Local read proof not mechanically verified'};smoke.updated_at=now;writeStore(s)}}return smoke}
export async function verifyCapabilitySmoke(project:ProjectConfig,smokeId:string){return locked(async()=>{const s=readStore();const smoke=s.smokes.find(x=>x.smoke_id===smokeId);if(!smoke)throw new Error(`smoke ${smokeId} not found`);const registry=await getResourceRegistry(project);const ws=registry.workspaces.find(w=>w.workspace_id===smoke.workspace_id&&w.project_id===smoke.project_id);if(!ws)throw new Error('bound workspace not found');const now=new Date().toISOString();try{const text=await githubFile(ws.repository_url,ws.branch,smoke.temp_path);const ok=text===`nonce=${smoke.nonce}\nsource_sha256=${smoke.expected_source_sha256}\n`;smoke.capabilities.github_write={status:ok?'pass':'fail',checked_at:now,reason:ok?'Bridge independently fetched exact nonce file from canonical GitHub':'GitHub nonce file missing or content mismatch'};smoke.capabilities.github_read={status:ok?'pass':'fail',checked_at:now,reason:ok?'Committed nonce carries required GitHub-read proof':'GitHub read proof not mechanically verified'}}catch(e:any){smoke.capabilities.github_write={status:'fail',checked_at:now,reason:e.message};smoke.capabilities.github_read={status:'fail',checked_at:now,reason:e.message}}if(!smoke.verify_job_id){const snap=await getExecutorSnapshot({limit:100});const node=snap.nodes.find(n=>n.connection_status==='online'&&n.capabilities.includes('fs.read'));if(!node){smoke.capabilities.workspace_read={status:'fail',checked_at:now,reason:'No online executor with fs.read for independent verification'};smoke.capabilities.workspace_write={status:'fail',checked_at:now,reason:'No online executor with fs.read for independent verification'}}else{const payload=await projectScopedExecutorPayload(smoke.workspace_id,smoke.project_id,{path:smoke.temp_path});const job=await createExecutorJob({workspace_id:smoke.workspace_id,project_id:smoke.project_id,node_id:node.node_id,task_id:smoke.task_id,action:'fs.read',payload,created_by:'capability-smoke-verifier'});smoke.verify_job_id=job.job_id}}smoke.updated_at=now;writeStore(s);return smoke})}
export async function reportCapabilityCleanup(smokeId:string){return locked(async()=>{const s=readStore();const smoke=s.smokes.find(x=>x.smoke_id===smokeId);if(!smoke)throw new Error(`smoke ${smokeId} not found`);smoke.cleanup_status='reported';smoke.updated_at=new Date().toISOString();writeStore(s);return smoke})}
export function listCapabilitySmokes(){return readStore().smokes}
