import { Router, Request, Response } from 'express';
import crypto from 'crypto';
import { getProject } from './db.js';
import { getResourceRegistry, removeResourceTarget, upsertResourceTarget } from './resourceRegistry.js';
import { getWorkspaceRegistry, projectLocalPath, upsertWorkspace } from './workspaceRegistry.js';
import { buildWakeQueue } from './wakeQueue.js';
import { queueProjectSetup } from './projectSetup.js';
import { getCapabilitySmoke, listCapabilitySmokes, reportCapabilityCleanup, startCapabilitySmoke, verifyCapabilitySmoke } from './capabilitySmoke.js';
export const resourceRegistryRouter = Router();
function normalizeRepoUrl(raw: unknown){const value=String(raw||'').trim();if(!value)throw new Error('repository_url is required');let parsed:URL;try{parsed=new URL(value)}catch{throw new Error('repository_url must be a valid absolute URL')}if(parsed.protocol!=='https:'&&parsed.protocol!=='http:')throw new Error('repository_url must use http or https');parsed.hash='';parsed.search='';parsed.pathname=parsed.pathname.replace(/\.git$/i,'').replace(/\/+$/,'');return parsed.toString().replace(/\/$/,'')}
function deriveProjectName(repositoryUrl:string){const parts=new URL(repositoryUrl).pathname.split('/').filter(Boolean);return parts.at(-1)||'Bridge Project'}
function makeWorkspaceId(repositoryUrl:string){const parsed=new URL(repositoryUrl),slug=parsed.pathname.split('/').filter(Boolean).join('-').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,54)||'project',digest=crypto.createHash('sha256').update(repositoryUrl).digest('hex').slice(0,8);return `workspace-${slug}-${digest}`}
resourceRegistryRouter.get('/',async(_req,res)=>{try{const project=await getProject();res.json({ok:true,...(await getResourceRegistry(project))})}catch(err:any){res.status(500).json({ok:false,error:err.message})}});
resourceRegistryRouter.get('/wake-queue',async(_req,res)=>{try{const project=await getProject(),events=await buildWakeQueue(project);res.json({ok:true,events,event_count:events.length,generated_at:new Date().toISOString()})}catch(err:any){res.status(500).json({ok:false,error:err.message})}});
resourceRegistryRouter.post('/projects',async(req,res)=>{try{const project=await getProject(),repositoryUrl=normalizeRepoUrl(req.body?.repository_url),suppliedWorkspaceId=String(req.body?.workspace_id||'').trim(),creating=!suppliedWorkspaceId,workspaceId=suppliedWorkspaceId||makeWorkspaceId(repositoryUrl),projectId=String(req.body?.project_id||'').trim()||workspaceId.replace(/^workspace-/,'project-'),projectName=String(req.body?.project_name||'').trim()||deriveProjectName(repositoryUrl),branch=String(req.body?.branch||'').trim()||'main',workspace=await upsertWorkspace(project,{workspace_id:workspaceId,project_id:projectId,project_name:projectName,repository_url:repositoryUrl,branch,local_path:creating?projectLocalPath(projectName,projectId):undefined,execution_target:req.body?.execution_target,setup_required:creating?true:undefined}),setup=creating?await queueProjectSetup(workspace):{status:'not_required' as const,job_id:null,error:null};res.status(201).json({ok:true,workspace,pc_setup:setup.status,pc_setup_job_id:setup.job_id,pc_setup_error:setup.error})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.post('/projects/:workspace_id/setup',async(req,res)=>{try{const project=await getProject(),registry=await getWorkspaceRegistry(project),workspace=registry.workspaces.find(item=>item.workspace_id===req.params.workspace_id);if(!workspace){res.status(404).json({ok:false,error:`workspace ${req.params.workspace_id} not found`});return}if(!workspace.setup_required){res.json({ok:true,setup:{status:'not_required',job_id:null,error:null}});return}res.json({ok:true,setup:await queueProjectSetup(workspace,{retryFailed:true})})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.post('/targets',async(req,res)=>{try{const project=await getProject(),target=await upsertResourceTarget(project,{workspace_id:req.body?.workspace_id,resource_url:req.body?.resource_url,label:req.body?.label});res.status(201).json({ok:true,target})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.delete('/targets/:target_id',async(req,res)=>{try{const removed=await removeResourceTarget(req.params.target_id);if(!removed){res.status(404).json({ok:false,error:`target ${req.params.target_id} not found`});return}res.json({ok:true,removed:req.params.target_id})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.get('/capability-smokes',async(_req,res)=>res.json({ok:true,smokes:listCapabilitySmokes()}));
resourceRegistryRouter.post('/workspaces/:workspace_id/targets/:target_id/capability-smokes',async(req,res)=>{try{const project=await getProject();res.status(201).json({ok:true,smoke:await startCapabilitySmoke(project,req.params.workspace_id,req.params.target_id)})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.get('/capability-smokes/:smoke_id',async(req,res)=>{try{const project=await getProject(),smoke=await getCapabilitySmoke(project,req.params.smoke_id);if(!smoke){res.status(404).json({ok:false,error:'smoke not found'});return}res.json({ok:true,smoke})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.post('/capability-smokes/:smoke_id/verify',async(req,res)=>{try{const project=await getProject();res.json({ok:true,smoke:await verifyCapabilitySmoke(project,req.params.smoke_id)})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
resourceRegistryRouter.post('/capability-smokes/:smoke_id/cleanup',async(req,res)=>{try{const project=await getProject();res.json({ok:true,smoke:await reportCapabilityCleanup(project,req.params.smoke_id)})}catch(err:any){res.status(400).json({ok:false,error:err.message})}});
