import React, { useEffect, useMemo, useState } from 'react';
import { Check, Pencil, Plus, X } from 'lucide-react';
import { ProjectSetupStatusBar } from './ProjectSetupStatusBar.js';

interface ResourceTarget { target_id:string; provider:'chatgpt'|'google-ai-studio'; resource_url:string; workspace_id:string; project_id:string; label:string; agent_instance_id:string; connection_status:'registered'|'active'|'idle'|'offline'; }
interface ResourceWorkspace { workspace_id:string; project_id:string; project_name:string; repository_url:string; branch:string; studio_targets:ResourceTarget[]; chatgpt_targets:ResourceTarget[]; }
interface ResourceSnapshot { workspaces:ResourceWorkspace[]; }
const KEY='bridge.resource.activeWorkspace';
function readActive(){try{return localStorage.getItem(KEY)||''}catch{return''}}
function writeActive(v:string){try{localStorage.setItem(KEY,v)}catch{}}
function AgentChip({target,name,tone}:{target?:ResourceTarget;name:string;tone:'gpt'|'studio'}){if(!target)return null;const active=target.connection_status==='active';return <div className="inline-flex h-9 shrink-0 items-center gap-1.5 rounded-full border border-border bg-surface px-2.5 text-[11px]"><span className={`size-1.5 rounded-full ${tone==='gpt'?'bg-gpt':'bg-studio'} ${active?'animate-pulse-dot':''}`}/><span className="font-medium">{name}</span><span className="text-muted-foreground">{active?'active':target.connection_status}</span></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-1 block text-[10px] uppercase tracking-wider text-muted-foreground">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-[13px] outline-none"/></label>}
export const ProjectRouterV2:React.FC=()=>{const[snapshot,setSnapshot]=useState<ResourceSnapshot|null>(null),[activeId,setActiveId]=useState(readActive),[showCreate,setShowCreate]=useState(false),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[name,setName]=useState(''),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[newName,setNewName]=useState(''),[newRepo,setNewRepo]=useState(''),[newChat,setNewChat]=useState('');
const load=async()=>{try{const r=await fetch('/api/resource-registry',{cache:'no-store'});if(!r.ok)return;const d=await r.json();const next={workspaces:d.workspaces||[]};setSnapshot(next);const wanted=readActive()||activeId;if(!next.workspaces.some((w:ResourceWorkspace)=>w.workspace_id===wanted)&&next.workspaces[0])select(next.workspaces[0]);}catch{}};useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);const current=useMemo(()=>snapshot?.workspaces.find(w=>w.workspace_id===activeId)||snapshot?.workspaces[0]||null,[snapshot,activeId]);useEffect(()=>{if(current){setName(current.project_name);setRepo(current.repository_url);setBranch(current.branch||'main')}},[current?.workspace_id]);
const select=(w:ResourceWorkspace)=>{setActiveId(w.workspace_id);writeActive(w.workspace_id);setEditing(false);window.dispatchEvent(new CustomEvent('bridge:active-project-changed',{detail:{workspace_id:w.workspace_id,project_id:w.project_id}}))};
const create=async()=>{if(!newRepo.trim()||busy)return;setBusy(true);try{const r=await fetch('/api/resource-registry/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:newRepo.trim(),project_name:newName.trim()||undefined,execution_target:'pc'})});const d=await r.json();if(!r.ok)throw Error(d.error||'create failed');if(newChat.trim())await fetch('/api/resource-registry/targets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:d.workspace.workspace_id,resource_url:newChat.trim(),label:'Sol 5.6'})});setShowCreate(false);setNewName('');setNewRepo('');setNewChat('');select(d.workspace);await load()}finally{setBusy(false)}};
const save=async()=>{if(!current||!name.trim()||!repo.trim()||busy)return;setBusy(true);try{const r=await fetch('/api/resource-registry/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:current.workspace_id,project_id:current.project_id,project_name:name.trim(),repository_url:repo.trim(),branch:branch.trim()||'main',execution_target:'pc'})});if(!r.ok)throw Error('save failed');setEditing(false);await load()}finally{setBusy(false)}};
return <section className="shrink-0 border-b border-border bg-background/60"><div className="no-scrollbar flex items-center gap-2 overflow-x-auto px-3 py-2 sm:px-4">{(snapshot?.workspaces||[]).map(w=>{const active=w.workspace_id===current?.workspace_id;return <button key={w.workspace_id} onClick={()=>select(w)} className={`inline-flex h-9 shrink-0 items-center gap-2 rounded-full border px-3 text-[13px] font-medium ${active?'border-gpt/40 bg-gpt/10 text-gpt':'border-border bg-surface text-muted-foreground'}`}><span className={`size-1.5 rounded-full ${active?'bg-gpt':'bg-muted-foreground/50'}`}/><span className="max-w-36 truncate">{w.project_name}</span></button>})}<button onClick={()=>setShowCreate(v=>!v)} title="Add project" className="grid size-9 shrink-0 place-items-center rounded-full border border-dashed border-border text-muted-foreground"><Plus className="size-4"/></button><AgentChip target={current?.studio_targets[0]} name="Gemini 3.8 Flash" tone="studio"/><AgentChip target={current?.chatgpt_targets[0]} name="Sol 5.6" tone="gpt"/><ProjectSetupStatusBar/>{current&&<button onClick={()=>setEditing(v=>!v)} title="Edit project" className="grid size-9 shrink-0 place-items-center rounded-full border border-border text-muted-foreground"><Pencil className="size-3.5"/></button>}</div>
{showCreate&&<div className="mx-3 mb-2 grid gap-2 rounded-xl border border-border bg-surface p-3 sm:mx-4 sm:grid-cols-3"><Field label="Project name" value={newName} onChange={setNewName}/><Field label="GitHub repo URL" value={newRepo} onChange={setNewRepo}/><Field label="ChatGPT URL" value={newChat} onChange={setNewChat}/><div className="flex gap-2 sm:col-span-3 sm:justify-end"><button onClick={()=>setShowCreate(false)} className="h-9 px-3 text-[12px] text-muted-foreground"><X className="mr-1 inline size-3.5"/>Cancel</button><button disabled={!newRepo.trim()||busy} onClick={create} className="h-9 rounded-lg bg-primary px-3 text-[12px] text-primary-foreground disabled:opacity-40"><Check className="mr-1 inline size-3.5"/>Save</button></div></div>}
{current&&editing&&<div className="mx-3 mb-2 grid gap-2 rounded-xl border border-border bg-surface p-3 sm:mx-4 sm:grid-cols-3"><Field label="Project name" value={name} onChange={setName}/><Field label="Repo URL" value={repo} onChange={setRepo}/><Field label="Branch" value={branch} onChange={setBranch}/><div className="flex gap-2 sm:col-span-3 sm:justify-end"><button onClick={()=>setEditing(false)} className="h-9 px-3 text-[12px] text-muted-foreground">Cancel</button><button disabled={busy} onClick={save} className="h-9 rounded-lg bg-primary px-3 text-[12px] text-primary-foreground disabled:opacity-40">Save</button></div></div>}</section>};
