import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, FolderGit2, MonitorCog, RefreshCw, TriangleAlert } from 'lucide-react';

type SetupStatus = 'ready' | 'queued' | 'waiting_for_pc' | 'failed' | 'not_required';
interface WorkspaceSetupView { workspace_id:string; project_id:string; project_name:string; local_path:string; pc_setup_status:SetupStatus; pc_setup_job_id:string|null; pc_setup_error:string|null; }
const ACTIVE_WORKSPACE_KEY='bridge.resource.activeWorkspace';
function activeWorkspaceId(){try{return window.localStorage.getItem(ACTIVE_WORKSPACE_KEY)||'';}catch{return '';}}
function statusMeta(status:SetupStatus){if(status==='ready'||status==='not_required')return{label:'Ready',icon:CheckCircle2,tone:'text-gpt'};if(status==='queued')return{label:'Setting up',icon:RefreshCw,tone:'text-studio'};if(status==='failed')return{label:'Setup failed',icon:TriangleAlert,tone:'text-destructive'};return{label:'Waiting for PC',icon:MonitorCog,tone:'text-warn'};}
export const ProjectSetupStatusBar:React.FC=()=>{const[workspaces,setWorkspaces]=useState<WorkspaceSetupView[]>([]);const[activeId,setActiveId]=useState(activeWorkspaceId);const[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const response=await fetch('/api/resource-registry',{cache:'no-store'});if(!response.ok)return;const data=await response.json();setWorkspaces(data.workspaces||[]);setActiveId(activeWorkspaceId());}catch{}},[]);useEffect(()=>{load();const timer=window.setInterval(load,10000);const onProjectChanged=(event:Event)=>{const detail=(event as CustomEvent).detail||{};setActiveId(detail.workspace_id||activeWorkspaceId());void load();};window.addEventListener('bridge:active-project-changed',onProjectChanged as EventListener);return()=>{window.clearInterval(timer);window.removeEventListener('bridge:active-project-changed',onProjectChanged as EventListener);};},[load]);const current=useMemo(()=>workspaces.find(item=>item.workspace_id===activeId)||workspaces[0]||null,[workspaces,activeId]);if(!current)return null;const meta=statusMeta(current.pc_setup_status),Icon=meta.icon,canRetry=current.pc_setup_status==='waiting_for_pc'||current.pc_setup_status==='failed';const retry=async()=>{if(busy||!canRetry)return;setBusy(true);try{await fetch(`/api/resource-registry/projects/${encodeURIComponent(current.workspace_id)}/setup`,{method:'POST'});await load();}finally{setBusy(false);}};return <div className="inline-flex h-9 min-w-0 shrink-0 items-center gap-1.5 rounded-full border border-border bg-surface px-2.5 text-[11px]"><FolderGit2 className="size-3.5 shrink-0 text-muted-foreground"/><span className="max-w-40 truncate font-medium text-foreground" title={current.local_path}>{current.local_path}</span><span className={`inline-flex shrink-0 items-center gap-1 ${meta.tone}`} title={current.pc_setup_error||undefined}><Icon className={`size-3 ${current.pc_setup_status==='queued'?'animate-spin':''}`}/>{meta.label}</span>{canRetry&&<button onClick={retry} disabled={busy} className="shrink-0 text-[10px] font-medium text-foreground disabled:opacity-40">{current.pc_setup_status==='failed'?'Retry':'Setup'}</button>}</div>;};
